### ISSUE TITLE
When input a pcap file it shows float division by zero

### ISSUE THREAD

**Issue by superjdz** [alekzandr/flowmeter#2]
![image](https://user-images.githubusercontent.com/36131558/60757187-d219d880-a039-11e9-8935-08ad65c80022.png)

And the pcap file is here

[norm2.zip](https://github.com/alekzandr/flowmeter/files/3364729/norm2.zip)

Thank you for helping me !

**Comment by alekzandr** [comment]
Sorry, was out of the country and had limited internet. I'll begin taking a look now.

**Comment by alekzandr** [comment]
I wasn't able to reproduce your error. I would recommend trying to run it outside of jupyter notebooks. There are known issues being worked on how notebooks handle certain areas that have been optimized for speed.

**Comment by superjdz** [comment]
Thank you for your reply! I taken advantage of CICFlowMeter in my work.  And I'll try your advice.
